import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// 常に監視状態 => 場所指定　supabase-listenerを指定
import SupabaseListener from './components/supabase-listener'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// レイアウト
const RootLayout = ({ children }: { children: React.ReactNode }) => {
  
  return (
    <html>
      <body className={inter.className}>
        {/* カーソル極力なし設定 */}
        <div className="flex flex-col min-h-screen">
                    {/* 呼び出し部 */}
                    <SupabaseListener />
                    

                    


          <main className="flex-1 container max-w-screen-sm mx-auto px-1 py-5">{children}</main>

           <footer className="py-5">
            <div className="text-center text-sm">
              Copyright © All rights reserved | rakuraku-sc-system
            </div>
          </footer>

        </div>
      </body>
    </html>
  )
}

export default RootLayout
